
package puntodeventa;

import archivos.AbrirArchivo;
import finanzas.Ventas;
import static java.lang.Double.parseDouble;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import personas.*;

/*
 * Clase Venta
 * Autor 1: Fabián Camp Mussa A01378565.
 * Autor 2: José Javier Rodríguez Mota A01372812.
 * Autor 3: Lenin Silva Gutiérrez A01373214.
 * Fecha: mayo 12, 2017.
 * Proyecto final
 */
public class Venta extends javax.swing.JFrame {
    DefaultListModel<String> model = new DefaultListModel<>();
    /**
     * Creates new form Venta
     */
    public Empleado e;
    public Venta() {
        initComponents();
    }
    public Venta(Empleado e) {
        initComponents();
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        productosCombo = new javax.swing.JComboBox<>();
        addProduct = new javax.swing.JButton();
        payCard = new javax.swing.JButton();
        payCash = new javax.swing.JButton();
        totalText = new javax.swing.JLabel();
        cambioText = new javax.swing.JLabel();
        factura = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProduct = new javax.swing.JList<>();
        delElement = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido a Tec Store.");

        productosCombo.setModel(new javax.swing.DefaultComboBoxModel<>(AbrirArchivo.getArticulos()));
        productosCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productosComboItemStateChanged(evt);
            }
        });
        productosCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosComboActionPerformed(evt);
            }
        });

        addProduct.setText("+");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        payCard.setText("Pago con tarjeta");
        payCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payCardActionPerformed(evt);
            }
        });

        payCash.setText("Pago en efectivo");
        payCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payCashActionPerformed(evt);
            }
        });

        totalText.setText("Total: 0.0");

        cambioText.setText("Cambio: 0.0");

        factura.setText("Factura");

        listaProduct.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaProduct);

        delElement.setText("Eliminar elemento");
        delElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delElementActionPerformed(evt);
            }
        });

        jButton1.setText("Corte de caja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(totalText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(payCard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(payCash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cambioText)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(delElement))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(productosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factura)
                    .addComponent(delElement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payCard)
                    .addComponent(payCash)
                    .addComponent(cambioText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productosComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productosComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_productosComboItemStateChanged

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        
        String elemento = this.productosCombo.getSelectedItem().toString();
        model.addElement(elemento);
        this.listaProduct.setModel(model);
        double precio = parseDouble(elemento.substring(elemento.indexOf("$")+1));
        precio+=parseDouble(this.totalText.getText().substring(7));
        this.totalText.setText("Total: "+precio);
        
        
    }//GEN-LAST:event_addProductActionPerformed

    private void payCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payCashActionPerformed
        
        double pago = parseDouble(JOptionPane.showInputDialog("Efectivo:"));
        if(this.factura.isSelected())
        {
          Clientes client = new Clientes();
          client.setVisible(true);
        }
        double precio = parseDouble(this.totalText.getText().substring(7));
        String[] venta = new String[model.toArray().length];
            for (int x=0; x<model.toArray().length;x++)
            {
                venta[x]=model.toArray()[x].toString();
            }
        Ventas m = new Ventas(venta,precio,e, "Efectivo");
        this.cambioText.setText("Cambio: "+(pago-parseDouble(this.totalText.getText().substring(7))));
        JOptionPane.showMessageDialog(null, this.cambioText.getText());
        this.cambioText.setText("Cambio: 0.00");
        this.totalText.setText("Cambio: 0.00");
        this.model.removeAllElements();
    }//GEN-LAST:event_payCashActionPerformed

    private void payCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payCardActionPerformed
       if(this.factura.isSelected())
       {
           Clientes client = new Clientes();
           client.setVisible(true);
           
       }
       JOptionPane.showMessageDialog(null, "Esperando PinPad...");
       JOptionPane.showMessageDialog(null, "Pago realizado exitosamente.");
       double precio = parseDouble(this.totalText.getText().substring(7));
       String[] venta = new String[model.toArray().length];
            for (int x=0; x<model.toArray().length;x++)
            {
                venta[x]=model.toArray()[x].toString();
            }
       Ventas m = new Ventas(venta,precio,e, "Tarjeta");
       this.cambioText.setText("Cambio: 0.00");
       this.totalText.setText("Cambio: 0.00");
       this.model.removeAllElements();
    }//GEN-LAST:event_payCardActionPerformed

    private void productosComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productosComboActionPerformed

    private void delElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delElementActionPerformed
        String elemento = this.listaProduct.getSelectedValue();
        double precio = parseDouble(this.totalText.getText().substring(7));
        precio-=parseDouble(elemento.substring(elemento.indexOf("$")+1));
        this.totalText.setText("Total: "+precio);
        this.model.remove(this.listaProduct.getSelectedIndex());
        
    }//GEN-LAST:event_delElementActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(null, "En la caja debe haber: "+this.e.corteCaja()[0]+".");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JLabel cambioText;
    private javax.swing.JButton delElement;
    private javax.swing.JCheckBox factura;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JList<String> listaProduct;
    private javax.swing.JButton payCard;
    private javax.swing.JButton payCash;
    private javax.swing.JComboBox<String> productosCombo;
    private javax.swing.JLabel totalText;
    // End of variables declaration//GEN-END:variables
}
